name: CD

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2.1.0
      with:
        repository: VaagenIM/docs.iktim.no
        event-type: doc_update
